name: 'Upload MC resource pack'
description: 'Uploads resource packs to https://mc-packs.net/ and returns download link'
branding:
  icon: 'upload-cloud'  # Choose an appropriate icon from GitHub's Octicons
  color: 'blue'
inputs:
  path:
    description: 'Resource pack path'
    required: true
    default: ''
outputs:
  url:
    description: 'resource pack download url'
  hash:
    description: 'resource pack hash-code'
runs:
  using: 'node12'
  main: 'dist/index.js'